language: ruby

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - jruby-19mode
  - ree

bundler_args: --without release development

env: CI="travis"

script: bundle exec rake spec:ci

notifications:
  email: false
  flowdock: 1da4416b8ff98d1880986472428b1b1b

services:
  - mongodb

branches:
  only:
    - master
    - 1.x-stable
    - 2.x-stable
