language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
  - ruby-head
  - jruby-19mode
  - jruby-head

jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8

install: ruby -S bundle install --without release development

env:
  global:
    - CI="travis"
  matrix:
    - MONGODB=2.4.12
    - MONGODB=2.6.7
    - MONGODB=3.0.0-rc8

before_script:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz -O /tmp/mongodb.tgz
  - tar -xvf /tmp/mongodb.tgz
  - mkdir /tmp/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath /tmp/data --bind_ip 127.0.0.1 --auth &> /dev/null &

script: bundle exec rake spec:ci

notifications:
  email: false
  flowdock: 1da4416b8ff98d1880986472428b1b1b

branches:
  only:
    - master
    - 1.x-stable

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  exclude:
    - rvm: 1.9.3
      jdk: openjdk7
    - rvm: 1.9.3
      jdk: oraclejdk8
    - rvm: 2.0.0
      jdk: openjdk7
    - rvm: 2.0.0
      jdk: oraclejdk8
    - rvm: 2.1.5
      jdk: openjdk7
    - rvm: 2.1.5
      jdk: oraclejdk8
    - rvm: 2.2.0
      jdk: openjdk7
    - rvm: 2.2.0
      jdk: oraclejdk8
    - rvm: ruby-head
      jdk: openjdk7
    - rvm: ruby-head
      jdk: oraclejdk8
